# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1b9475f5326f8ebb60274b2e2d5e102ad5c967af9d3d412c7791e8bb6841fb1509de3a7ce5c00e5f48cb4be7d522fd0f3121305d5b4204c800f28060d740f5

test:
  secret_key_base: a3fda4d1e1c0e54fcfc84a2e5f1e0e740abfef0f07da60bbb877119afce7d995cd9fbaca980651a92e60d536e2aeea4266c944846adf59cc2d92fb38e484e992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
